name: tests

on: [push, pull_request]

jobs:
  perl:
    runs-on: ubuntu-latest
    container:
      image: perl:latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: cpanm . -v -v 
      - name: test
        run: perl test/runtests.pl
